### PR TITLE
[hotfix] Remove runtime exceptions from application code

### LINKED ISSUE #407: [CLI] Validating returns a stack trace
A stack trace should not be shown when validating an invalid file
```bash
❯❯❯ temple validate test.temple
java.lang.RuntimeException: Templefile could not be parsed
string matching regex '[A-Z]' expected but 'a' found
1 | a;sdlkfj
    ^
temple.Application$.$anonfun$validate$1(Application.scala:36)
scala.util.Either.fold(Either.scala:190)
temple.utils.MonadUtils$FromEither.fromEither(MonadUtils.scala:9)
temple.Application$.validate(Application.scala:35)
temple.Main$.delayedEndpoint$temple$Main$1(Main.scala:20)
temple.Main$delayedInit$body.apply(Main.scala:9)
scala.Function0.apply$mcV$sp(Function0.scala:39)
scala.Function0.apply$mcV$sp$(Function0.scala:39)
scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
scala.App.$anonfun$main$1(App.scala:73)
scala.App.$anonfun$main$1$adapted(App.scala:73)
scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
scala.collection.AbstractIterable.foreach(Iterable.scala:921)
scala.App.main(App.scala:73)
scala.App.main$(App.scala:71)
temple.Main$.main(Main.scala:9)
temple.Main.main(Main.scala)
```

### LINKED ISSUE #408: [CLI] Invalid subcommands should not throw an error, but rather print usage
When running an invalid command, the correct usage should be shown (as Docker does), instead of printing a stack trace
```
› temple gen
java.lang.IllegalArgumentException: Excess arguments provided: 'gen'
temple.TempleConfig.$anonfun$new$1(TempleConfig.scala:10)
org.rogach.scallop.ScallopConfBase.onError(ScallopConfBase.scala:456)
org.rogach.scallop.ScallopConfBase.verifyBuilder(ScallopConfBase.scala:409)
org.rogach.scallop.ScallopConfBase.verify(ScallopConfBase.scala:831)
temple.TempleConfig.<init>(TempleConfig.scala:46)
temple.Main$.delayedEndpoint$temple$Main$1(Main.scala:17)
temple.Main$delayedInit$body.apply(Main.scala:9)
scala.Function0.apply$mcV$sp(Function0.scala:39)
scala.Function0.apply$mcV$sp$(Function0.scala:39)
scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
scala.App.$anonfun$main$1(App.scala:73)
scala.App.$anonfun$main$1$adapted(App.scala:73)
scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
scala.collection.AbstractIterable.foreach(Iterable.scala:921)
scala.App.main(App.scala:73)
scala.App.main$(App.scala:71)
temple.Main$.main(Main.scala:9)
temple.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by jaylees14**
- Defines a specific exception for invalid Templefiles - test with `temple validate invalid.temple`
- Defines a specific exception for invalid arguments - test with `temple COMMAND`

Closes #407 
Closes #408

### CODE REVIEW

**Review by Lewiky — APPROVED** [review]
Nice one

File: src/main/scala/temple/Main.scala [hunk 1]
```diff
@@ -26,6 +27,8 @@ object Main extends App {
     case error: FileAlreadyExistsException  => exit(s"File already exists: ${error.getMessage}")
     case error: NoSuchFileException         => exit(s"File not found: ${error.getMessage}")
     case error: InvalidPackageNameException => exit(s"Package name isn't valid: ${error.getMessage}")
+    case error: InvalidTemplefileException  => exit(error.getMessage)
+    case error: IllegalArgumentException    => exit(error.getMessage)
```
Comment (c-harding) [inline src/main/scala/temple/Main.scala]: I know this is going to make the control flow slightly messier, but I feel this `IllegalArgumentException` should be around `new TempleConfig`, as IllegalArgumentException could well be thrown by the rest of the program too

**Review by c-harding — APPROVED** [review]
