### PR TITLE
[fix][regen] Add buildFilenameSeq function

### LINKED ISSUE #374: Regeneration filter crashes on hidden files
To reproduce:

* `mkdir example`
* `temple generate -o example path/to/templefile`

If the `example` directory has a hidden file, such as `.DS_Store`, the regeneration filter crashes

### PR DESCRIPTION
**Pull request by Lewiky**
Adds a `buildFilenameSeq` function to `FileUtils` which mirrors `buildFileMap`, except it just returns a sequence of the `File` objects found rather than their contents.

Closes #374

### CODE REVIEW

File: src/main/scala/temple/utils/FileUtils.scala [hunk 1]
```diff
@@ -105,4 +112,36 @@ object FileUtils {
...
     foundFiles
   }
+
+  /**
+    * Build a sequence of filenames of files present in the provided filepath
+    * @param path The root path to explore
+    * @param cwd The location to give paths relative to
+    * @return A sequence of filenames, relative to the provided path
+    */
+  private def buildFilenameMap(path: Path, cwd: Path): Seq[File] = {
```
Comment (c-harding) [inline src/main/scala/temple/utils/FileUtils.scala]: is this a `Map`? Odd name for the function

File: src/main/scala/temple/utils/FileUtils.scala [hunk 2]
```diff
@@ -105,4 +112,36 @@ object FileUtils {
...
+    var foundFiles: Seq[File] = Seq.empty
```
Comment (c-harding) [inline src/main/scala/temple/utils/FileUtils.scala]: I realise it’s the same for the map, but this would be better served by a val of type `mutable.Buffer`, to avoid all the list copying.

File: src/main/scala/temple/utils/FileUtils.scala [hunk 3]
```diff
@@ -105,4 +112,36 @@ object FileUtils {
...
+        }
+
+        override def visitFileFailed(file: Path, exc: IOException): FileVisitResult =
+          throw exc
+
+        override def postVisitDirectory(dir: Path, exc: IOException): FileVisitResult =
+          FileVisitResult.CONTINUE
+      },
+    )
+    foundFiles
```
Comment (c-harding) [inline src/main/scala/temple/utils/FileUtils.scala]: (and then foundFiles.toSeq here)

**Review by c-harding — APPROVED** [review]
nice

File: src/main/scala/temple/utils/FileUtils.scala (hunk 1 above)
Comment (Lewiky) [reply src/main/scala/temple/utils/FileUtils.scala]: Whoops renamed the other but not this one

**Review by jaylees14 — APPROVED** [review]
